spring:
  application:
    name: authentication-service
  profiles:
    active: local

jwt:
  secret-key: my-secret-key-for-development-purpose-only
  expiration: 3600000 # 60 minutes

refresh-token:
  expiration: 604800000 # 7 days